src/NodaTime.Web/Providers/MarkdownLoader.cs

Use the unversioned serialization API in links from the user guide

---

src/NodaTime.Web/Controllers/HomeController.cs
src/NodaTime.Web/NodaTime.Web.csproj
src/NodaTime.Web/Views/Benchmarks/CompareTypesByCommit.cshtml
src/NodaTime.Web/Views/Benchmarks/CompareTypesByEnvironment.cshtml
src/NodaTime.Web/Views/Home/IanaTimeZones.cshtml
src/NodaTime.Web/Views/_ViewImports.cshtml

This isn't linked anywhere yet, but I'm adding it for the sake of feedback.
See #10 for the feature request.

Prototype of time zone display page

---

src/NodaTime.Web/Configuration/StorageOptions.cs
src/NodaTime.Web/Controllers/DownloadsController.cs
src/NodaTime.Web/Services/BenchmarkRepository.cs
src/NodaTime.Web/Services/GoogleStorageReleaseRepository.cs
src/NodaTime.Web/Services/IReleaseRepository.cs
src/NodaTime.Web/Services/ReleaseRepository.cs
src/NodaTime.Web/Services/TzdbRepository.cs
src/NodaTime.Web/Startup.cs
src/NodaTime.Web/Views/Shared/_Layout.cshtml

Gets rid of a lot of hard-coding

Cleaner version handling

---

build/DocfxAnnotationGenerator/Program.cs

Check member documentation, but only for unstable releases

---

build/TocCombiner/Program.cs
build/TocCombiner/TocCombiner.csproj
build/Tools.sln
build/buildapidocs.sh

Sort TOCs when combining them

---

build/SandcastleXrefGenerator/SandcastleXrefGenerator.csproj
build/SnippetExtractor/SnippetExtractor.csproj
build/TocCombiner/TocCombiner.csproj
build/appveyor.sh
build/travis.sh

This uses the new ability to build projects targeting the .NET Framework on Linux: https://github.com/dotnet/designs/pull/33

Build the tools solution on CI

---

build/SnippetExtractor/SnippetRewriter.cs

Format snippets

---

build/SnippetExtractor/SnippetFileSyntaxTree.cs
build/SnippetExtractor/SnippetRewriter.cs

Fix warnings around symbol comparisons

---

src/NodaTime.Web/Markdown/unstable/index.json
src/NodaTime.Web/Markdown/unstable/installation.md
src/NodaTime.Web/Markdown/unstable/migration-to-3.md

Also update the installation page with updated system requirements.

Add a migration guide for Noda Time 3.0.

---

src/NodaTime.Web/Markdown/root/versions.md

Fix release date

---

src/NodaTime.Web/Markdown/developer/tzdb-file-format.md

Fix constant in NZD file format description

---

build/DocfxAnnotationGenerator/DocfxAnnotationGenerator.csproj
build/ReleaseDiffGenerator/ReleaseDiffGenerator.csproj
build/Sandbox/Sandbox.csproj
build/SnippetExtractor/Program.cs
build/SnippetExtractor/SnippetExtractor.csproj
build/deployment/Dockerfile
build/docfx_functions.sh
src/NodaTime.Web.SmokeTest/FetchPagesTest.cs
src/NodaTime.Web.SmokeTest/NodaTime.Web.SmokeTest.csproj
src/NodaTime.Web.Test/NodaTime.Web.Test.csproj
src/NodaTime.Web/Configuration/NetworkOptions.cs
src/NodaTime.Web/Controllers/HomeController.cs
src/NodaTime.Web/Helpers/DictionaryExtensions.cs
src/NodaTime.Web/Helpers/NodaHtmlHelpers.cs
src/NodaTime.Web/Models/MarkdownPage.cs
src/NodaTime.Web/Models/StructuredVersion.cs
src/NodaTime.Web/NodaTime.Web.csproj
src/NodaTime.Web/Services/BenchmarkRepository.cs
src/NodaTime.Web/Services/LocalStorageRepository.cs
src/NodaTime.Web/Services/MarkdownLoader.cs
src/NodaTime.Web/Services/ReleaseRepository.cs
src/NodaTime.Web/Services/TimerCache.cs
src/NodaTime.Web/Services/TzdbRepository.cs
src/NodaTime.Web/Startup.cs
src/NodaTime.Web/ViewModels/CompareTypesByEnvironmentViewModel.cs

Upgrade to ASP.NET Core 3.1

---

src/NodaTime.Web/Markdown/1.0.x/core-types.md
src/NodaTime.Web/Markdown/2.0.x/core-types.md

Update description of the core types page

---

src/NodaTime.Web/NodaTime.Web.csproj
src/NodaTime.Web/ViewModels/IanaRelease.cs
src/NodaTime.Web/Views/Home/TimeZones.cshtml

It's often useful to know the current offset and the next transition.

Add current time zone information

---

.github/workflows/build-docs.yml
build/Dockerfile

This will check everything out, then run docker build.
Currently the docker build is failing for me locally, with an error of "/bin/bash: line 1: buildweb.sh: command not found" - it's not clear to me why at the moment.

First pass at a github action

---

build/DocfxAnnotationGenerator/Program.cs

Order versions appropriately when annotating

---

build/Dockerfile
build/cloudbuild.yaml
src/NodaTime.Web/Controllers/DocumentationController.cs
src/NodaTime.Web/Controllers/TzdbController.cs
src/NodaTime.Web/Startup.cs
src/NodaTime.Web/appsettings.Production.json
src/NodaTime.Web/appsettings.SmokeTests.json
src/NodaTime.Web/appsettings.Staging.json
src/NodaTime.Web/appsettings.json

(These were accidentally in my personal fork.)

Update proper nodatime repo with Cloud Run changes

---

src/NodaTime.Web/Startup.cs
src/NodaTime.Web/appsettings.Production.json
src/NodaTime.Web/appsettings.Staging.json
src/NodaTime.Web/appsettings.json

When I removed it before, I was over-zealous.

Reinstate HTTPS redirection

---

src/NodaTime.Web/appsettings.Production.json

Rebase fail earlier on - in a way that *only* affected production :(

Fix production config

---

Directory.Build.props
Directory.Packages.props
build/DocfxAnnotationGenerator/DocfxAnnotationGenerator.csproj
build/DocfxYamlLoader/DocfxYamlLoader.csproj
build/SnippetExtractor/SnippetExtractor.csproj
build/TocCombiner/TocCombiner.csproj
src/NodaTime.TzValidate.NodaDump/NodaTime.TzValidate.NodaDump.csproj
src/NodaTime.Web.SmokeTest/NodaTime.Web.SmokeTest.csproj
src/NodaTime.Web.Test/NodaTime.Web.Test.csproj
src/NodaTime.Web/NodaTime.Web.csproj

This doesn't change the versions use - just puts them centrally

Use centralized package management
