nodatime/nodatime.org

build/buildapidocs.sh, build/docfx/docfx-unstable.json, build/docfx/namespaces.md
We can now remove NamespaceDoc.cs files from the other repos.
Fixes #12
=> Put namespace documentation in overwrite files

src/NodaTime.Web/Startup.cs
Anyone wanting to work on the web site should be able to clone and run now.
=> Make the API documentation optional, for the sake of development

build/finishautobuildweb.sh, src/NodaTime.Web/Startup.cs
- Redirect versions more liberally, so we don't need to check expected versions
- Use the release repository to work out the redirects for /api and /userguide
- Don't tell browsers to cache commit.txt or build.txt
- Put more information in commit.txt
=> Improve version handling and diagnostics

build/SandcastleXrefGenerator/Program.cs, build/SandcastleXrefGenerator/SandcastleXrefGenerator.csproj, build/Tools.sln, build/buildapidocs.sh, build/buildhistory.sh, build/docfx/docfx-web.json
Also modify the build scripts to use the generated map for Newtonsoft.Json
Fixes #13
Note that this *only* generates the map for types; that's all we need.
=> Simple xref generator for packages using Sandcastle

src/NodaTime.Web/Controllers/BenchmarksController.cs, src/NodaTime.Web/Helpers/DictionaryExtensions.cs, src/NodaTime.Web/Services/BenchmarkRepository.cs, src/NodaTime.Web/Services/IBenchmarkRepository.cs
Don't throw an exception if an unknown GUID is given - just return a 404
=> More robust handling for benchmarks

src/NodaTime.Web/Controllers/BenchmarksController.cs
(As found by GCP error reporting.)
We fail with an NRE if we're asked to compare benchmarks for a type
across different environments, in a commit where some environments
have tests for that type and some don't. Notably, BclDateTimeZone
used to have tests in Windows but not Linux.
=> Fix NRE in benchmarks

src/NodaTime.Web/Markdown/unstable/localdate-patterns.md
Also fix links to use docs.microsoft.com, in localdate-patterns. At some point we should probably fix all of them.
This is documentation for https://github.com/nodatime/nodatime/pull/1473
=> Add month/date standard pattern to documentation.

src/NodaTime.Web/Markdown/unstable/migration-to-3.md
- Document the potential for the removal of the
`AllowPartiallyTrustedCallers` attribute to be a breaking change (if
using .NET Framework and relying upon it, though it's still not
actually clear to me how the 'new' security model works).
- Document the (extremely minor) behaviour change introduced in
nodatime/nodatime#1527.
(The first of these as discussed in #78.)
=> Add some more caveats for the 2.x to 3.0 migration.

src/NodaTime.Web/Markdown/2.0.x/offset-patterns.md
Fixed a typo I found.
Not sure if this needs updating anywhere else, as I wasn't sure exactly how this section of the docs works.
=> Fix typo in offset-patterns.md

src/NodaTime.Web/Markdown/3.0.x/yearmonth-patterns.md
The `YearMonth` patterns page is currently linking to the API documentation for `LocalDate` at the very top. This corrects that link.
=> Link YearMonth patterns to correct API doco page

src/NodaTime.Web/Markdown/2.0.x/concepts.md
I _believe_ this is a hangover from when NodaTime had a base granularity of ticks, although I might be wrong!
=> Update "ticks" reference to nanosecond equivalent

build/buildapidocs.sh
Better to have a working website without snippets than one which
can't be updated...
=> Temporarily disable snippets entirely

build/finishautobuildweb.sh
This should help with the immediate problem of diagnosing why the
snippets aren't building, but will be useful long-term too.
=> Log all environment variables before building

build/ReleaseDiffGenerator/Program.cs
I still don't know why it doesn't get generated, but it's simplest to ignore it.
=> Exclude IXmlSerializable.GetSchema from diff

.config/dotnet-tools.json, build/DocfxAnnotationGenerator/DocfxAnnotationGenerator.csproj, build/DocfxAnnotationGenerator/Program.cs, build/DocfxYamlLoader/DocfxYamlLoader.csproj, build/DocfxYamlLoader/Release.cs, build/ReleaseDiffGenerator/ReleaseDiffGenerator.csproj, build/TocCombiner/Program.cs, build/TocCombiner/TocCombiner.csproj, build/Tools.sln
We can't upgrade to the latest version yet, as the TOC format has changed. We'll need to rewrite *old* TOCs to be in the new format first, as well as changing how we handle them. Sigh.
(This has led me to bump everything to .NET 6 though, which is a good thing regardless.)
=> Fixes for docfx

.config/dotnet-tools.json
2.63.0 builds, but the changed templates need js/css that we don't currently serve.
This will take longer to fix (and we might as well do it at the same time as going up to 2.66.2).
=> Revert to docfx 2.62.2 for now

build/buildapidocs.sh, build/testing-docfx.json
Without these changes, using saucecontrol.InheritDoc causes issues - but they were already inherent in this build.
Fundamentally there's a weakness in docfx here (yet again) but this should work round it.
=> Fix generation of local NodaTime.Testing metadata

build/buildapidocs.sh
(dotnet publish changed behaviour in .NET 8 to default to "Release", but we're looking for NodaTime.dll in "Debug")
=> Publish debug version of demo before extracting snippets

build/DocfxAnnotationGenerator/Program.cs, build/ReleaseDiffGenerator/Program.cs, build/testing-docfx.json
This means we can now get rid of all the special-casing that was in the tooling.
=> Enable explicit interface implementation docs for testing

build/Dockerfile, build/buildweb.sh, build/deployment/Dockerfile, build/deploytestbuild.sh
We may end up with a copy of this in each repo - or we could do a scheduled build (which is effectively what we have now).
The intention is to move the complete docs build into the Cloud.
=> Start of a new "build everything from scratch" Dockerfile

.github/workflows/test.yml, build/buildweb.sh, src/NodaTime.Web.SmokeTest/FetchPagesTest.cs, src/NodaTime.Web/appsettings.SmokeTests.json
- Run smoke tests in buildweb.sh, but using the fake data
- Run unit tests on PR/push
When all this is in place, we can ditch AppVeyor.
=> More testing

src/NodaTime.Web/appsettings.Production.json, src/NodaTime.Web/appsettings.Staging.json
This reverts commit 0c5e7fdfdd5fadf6bb24e527f10b37b3043b2511.
This *did* put the config in the right place, but it was somewhat cataclysmic to do so, leading to every request getting a 301.
I'll experiment separately with how to do this properly (with a build that doesn't take 10 minutes...)
=> Revert "Put the config in the right place..."

build/buildweb.sh
Without this, it looks like the server starts okay, but we can't fetch pages in the tests.
=> Specify smoke test URL directly in buildweb.sh

src/NodaTime.Web/Program.cs
This should fix the smoke test.
=> Start loading benchmarks on startup.

src/NodaTime.Web/Services/BenchmarkRepository.cs, src/NodaTime.Web/Views/Benchmarks/Index.cshtml, src/NodaTime.Web/appsettings.Production.json
We're getting a *lot* of traffic for benchmarks, despite robots.txt prohibiting traffic. It's not really of much use to anyone, so let's get rid of it.
=> Temporarily disable benchmarks
